plugins {
    id "com.gradleup.shadow" version "9.2.2"
}

def generatedResources = project(":common").file("src/main/generated/resources")
def commonBuiltinResourcePacks = project(":common").file("src/main/resources/resourcepacks")
def accessWidener = project(":common").file("src/main/resources/${mod_id}.accesswidener")

loom {
    accessWidenerPath = file(accessWidener)

    runs {
        client {
            programArgs("--username", "Dev")
        }
    }
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    api "net.fabricmc:fabric-loader:${fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    api "dev.architectury:architectury-fabric:${architectury_api_version}"

    implementation "dev.architectury:architectury-fabric:${architectury_api_version}"

    implementation "com.terraformersmc:modmenu:${mod_menu_version}" transitive false
    implementation "me.shedaniel.cloth:cloth-config:${cloth_config_version}"
    implementation "me.shedaniel.cloth:cloth-config-fabric:${cloth_config_version}" transitive false

    implementation "eu.pb4:polymer-core:${polymer_core_version}"
    implementation "eu.pb4:polymer-blocks:${polymer_core_version}"
    implementation "eu.pb4:polymer-resource-pack:${polymer_core_version}"
    implementation "eu.pb4:polymer-autohost:${polymer_core_version}"
    implementation "eu.pb4:polymer-virtual-entity:${polymer_core_version}"
    implementation "maven.modrinth:lootr:${lootr_modrinth_version_id}"
    implementation "maven.modrinth:68kWHuUF:${universal_ores_modrinth_version_id}"
    implementation "maven.modrinth:XLhounCW:${resource_library_modrinth_version_id}"
    implementation "maven.modrinth:GXPQteCw:${resource_nether_ores_modrinth_version_id}"

    //localRuntime "dev.emi:emi-fabric:${emi_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${rei_version}"
    //implementation "vazkii.patchouli:Patchouli:${patchouli_version_fabric}"
    //implementation "dev.emi:trinkets:${trinkets_version}"

    common(project(path: ':common')) { transitive false }
    shadowCommon project(path: ':common', configuration: 'transformProductionFabric')
}

processResources {
    inputs.property 'version', project.version

    from(commonBuiltinResourcePacks) {
        into("resourcepacks")
    }

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }

    from(accessWidener) {
        into("")
    }
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}
