# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
# Mod properties
mod_id=fabsservertweaks
mod_name=FabsServerTweaks
mod_authors=fabbe50
mod_version=1.2.0.0
mod_license=GNU LGPL 3.0
mod_description=Charting The Unknown Mod
maven_group=com.fabbe50
archives_name=fabsservertweaks
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=26.1.2
# Dependencies
architectury_api_version=20.0.6
fabric_loader_version=0.19.3
fabric_api_version=0.151.0+26.1.2
neoforge_version=26.1.2.76
neoforge_pr=
# Other Mods
patchouli_version_neoforge=
patchouli_version_fabric=
emi_version=
rei_version=26.1.819
jei_version=29.6.2.31
curios_version=
mod_menu_version=18.0.0-beta.1
trinkets_version=
cloth_config_version=26.1.154
polymer_core_version=0.16.5+26.1.2
lootr_modrinth_version_id=ig04GPJH
universal_ores_modrinth_version_id=sDBoLbAS
resource_library_modrinth_version_id=n5U6rSQE
resource_nether_ores_modrinth_version_id=bIAsMNwm