modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "fabsservertweaks"
version = "${version}"
displayName = "FabsServerTweaks"
authors = "fabbe50"
description = '''

'''
#logoFile = ""

[[dependencies.fabsservertweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.fabsservertweaks]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fabsservertweaks]]
modId = "architectury"
type = "required"
versionRange = "[17.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "fabsservertweaks.mixins.json"