plugins {
    id "com.gradleup.shadow" version "9.2.2"
}

def generatedResources = project(":common").file("src/main/generated/resources")
def commonBuiltinModPacks = project(":common").file("src/main/resources/mod")
def accessWidener = project(":common").file("src/main/resources/${mod_id}.accesswidener")

loom {
    accessWidenerPath = file(accessWidener)

    runs {
        data {
            serverData()
            programArgs("--all", "--mod", "${mod_id}")
            programArgs("--output", generatedResources.absolutePath)
            programArgs("--existing", project(":common").file("src/main/resources").absolutePath)
        }
    }
}

configurations {
    shadowCommon
    dev
}

artifacts {
    dev(jar)
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    neoForge "net.neoforged:neoforge:${neoforge_version}"
    api "dev.architectury:architectury-neoforge:${architectury_api_version}"

    implementation "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"

    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"
    runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}"
    compileOnly "me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${rei_version}"

    common(project(path: ':common')) { transitive false }
    shadowCommon project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    inputs.property 'version', project.version

    from(commonBuiltinModPacks) {
        into("mod")
    }

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}
